### ISSUE TITLE
"user_signed_in?" throws an exception with devise 3.5.6

### ISSUE THREAD

**Issue by acavalin** [mobalean/devise_ssl_session_verifiable#2]
I have this code in my application_controller.rb:

``` ruby
# /app/controllers/application_controller.rb
before_action :set_current_user
def set_current_user
  @user = user_signed_in? ? current_user : nil
end
```

With the new version of devise 3.5.6, it explodes :boom: in `user_signed_in?`, here is the backtrace:

```
#<ArgumentError: wrong number of arguments (0 for 2)>
/ruby-2.1.5/gems/devise-3.5.6/lib/devise/models/rememberable.rb:104:in `remember_me?'
/ruby-2.1.5/gems/devise_ssl_session_verifiable-3.0.4/lib/devise/controllers/ssl_session_verifiable.rb:52:in `ssl_session_verification_cookie_values'
/ruby-2.1.5/gems/devise_ssl_session_verifiable-3.0.4/lib/devise/controllers/ssl_session_verifiable.rb:30:in `set_ssl_session_verification_cookie'
/ruby-2.1.5/gems/devise_ssl_session_verifiable-3.0.4/lib/devise/hooks/ssl_session_verifiable.rb:4:in `block in <top (required)>'
/ruby-2.1.5/gems/warden-1.2.6/lib/warden/hooks.rb:14:in `call'
/ruby-2.1.5/gems/warden-1.2.6/lib/warden/hooks.rb:14:in `block in _run_callbacks'
/ruby-2.1.5/gems/warden-1.2.6/lib/warden/hooks.rb:9:in `each'
/ruby-2.1.5/gems/warden-1.2.6/lib/warden/hooks.rb:9:in `_run_callbacks'
/ruby-2.1.5/gems/warden-1.2.6/lib/warden/manager.rb:51:in `_run_callbacks'
/ruby-2.1.5/gems/warden-1.2.6/lib/warden/proxy.rb:179:in `set_user'
/ruby-2.1.5/gems/warden-1.2.6/lib/warden/proxy.rb:327:in `_perform_authentication'
/ruby-2.1.5/gems/warden-1.2.6/lib/warden/proxy.rb:104:in `authenticate'
/ruby-2.1.5/gems/devise-3.5.6/lib/devise/controllers/helpers.rb:124:in `current_user'
/ruby-2.1.5/gems/devise-3.5.6/lib/devise/controllers/helpers.rb:120:in `user_signed_in?'
/mnt/ramd/camelsoft/app/controllers/application_controller.rb:29:in `set_current_user'
[...]
```

The devise team has changed the `remember_me?` method, now it requires two parameters:
https://github.com/plataformatec/devise/blob/master/lib/devise/models/rememberable.rb#L99

The result is that the secure cookie is not set.

It throws an error also if I use `@user = current_user`

**Comment by mreinsch** [comment]
can you send a pull request? Thanks!

**Comment by acavalin** [comment]
I think I found a solution, take a look: https://github.com/mobalean/devise_ssl_session_verifiable/pull/3

**Comment by acavalin** [comment]
any news?
